### ISSUE TITLE
Please consider supporting ipython.parallel as a computation backend

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#119]
Migrated from mrocklin fork.  Originally posted by @phrrngtn

It would be super nice to be able to give a parallel.client.view  as the 'get' for a compute
my_array.compute(get=my_funky_view)

I think that this may help support #5 and it might also support funky topologies orthogonal to dask.

**Comment by mrocklin** [comment]
The current async scheduler assumes shared-memory or nearly-shared-memory communication.  We use multiprocessing only with workflows that don't involve intertask communication (e.g. dask.bag).

So one alteration of this issue might be use ipython views in nearly-embarassingly-parallel workflows.  That is quite doable.

Another alteration of this issue might be "make a distributed memory scheduler" which is something that I'm thinking about and have tiny experiments for but will probably hold off on making very usable for a while.

I do agree with you though that a future solution should easily hook in to IPython's parallel solution as a way to manage worker nodes.  There is a decent amount of tooling built up there.

This can't just be ipython parallel though (for non-trivial communication patterns).  Their abstractions don't really support point-to-point communication styles.  It's mostly master-slave.

**Comment by mrocklin** [comment]
I have "toy distributed scheduler" about two-to-three months out on my timeline.  I wouldn't be surprised if it was pushed out further.  Issues like this demonstrating interest bring the deadline closer.

**Comment by mrocklin** [comment]
Hi @phrrngtn, 

What kinds of operations / communication patterns interested you when using IPython parallel?  Is it only embarrassingly parallel tasks with some reductions?

**Comment by phrrngtn** [comment]
I used IPython parallel as as example only. I haven't given much if any thoughts to particular topologies and access patterns. My suggestion stems more from wanting to separate out the process creation from the dask. I am interested in having a bunch of engines/cores/job scheduler queues/whatever and being able to come up with a placement policy for the execution of parts of the graph in particular places. As an example, I may want to do a bunch of analysis and filtering close to the data but have a single worker processing the queue of results to be written back to a database. 

IPython parallel came to mind because I frequently have many IPython clients (notebook, CLI, QT GUI on windows) hanging off an IPython kernel that in turn has views  onto a mesh of processes, some of which are running in distinct network campuses separated by a high latency WAN. The inspiration for this came from reading dabeaz 2'nd tutorial on generators from a few years ago.

**Comment by phrrngtn** [comment]
great. I will take a look at it shortly (i.e. within 1 to 5 days)

**Comment by mrocklin** [comment]
Closing this due to #208
