### ISSUE TITLE
dask scheduler struggles with concatenate, following by indexing, followed by mean

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#137]
In xray, this looks something like the following:
```python
# concatenate a bunch of arrays along the "time" dimension
ds = xray.open_mfdataset('/Users/shoyer/data/era-interim/2t/*.nc', engine='scipy')
# this is 6-hourly data from 35 years; select out only data for January and take the mean 
ds.sel(time=ds['time.month'] == 1).mean()
```

The scheduler eats up all my memory when I try to compute the data. In contrast, `ds.mean()` (no intermediate indexing) works fine.

**Comment by mrocklin** [comment]
Ah, ok, so when we index with a list or array of booleans

    y = x[[5, 1, 2, 4]]

We don't have any knowledge about the size of blocks that we should produce.  Should we have one block of four? two blocks of two?  It's unclear.  Currently we follow the one-giant-block approach, hoping that either the list of items is not very large or that the blocking along the other dimensions manages the memory blowup.

This may be a fail case.  We have a very large list of elements to grab, so a very long block along one dimension.  Presumably this data is large enough so that cutting in the other dimensions doesn't save us.

To resolve this problem we probably need a heuristic to determine good output block sizes when given large indexing lists / array-of-bools.

**Comment by shoyer** [comment]
I wonder if we can do something like the current slicing logic: simply preserve the existing blocks, if possible (dropping unused blocks). That would work as long as indexing doesn't do anything pathological like accessing values out of order.

**Comment by mrocklin** [comment]
I view indexing with lists as likely to span different blocks.  Indexing with arrays of booleans though might be a different story.  Perhaps in the list case we do one-giant-block while with arrays of booleans we do all of your original blocks.

**Comment by shoyer** [comment]
Hmm. With xray we currently canonicalize all indexing to use integers instead of booleans. I'm not sure it's a good idea to make behavior that relies on that distinction...

**Comment by shoyer** [comment]
Here's another choice that avoids heuristics: use the size of the largest block as the blockshape along the indexed dimension.

**Comment by mrocklin** [comment]
That could work.  We'll still run into issues when the list is out-of-order but hopefully large out-of-order lists are rare.

**Comment by shoyer** [comment]
@mrocklin I don't follow you on the issue for out of order large lists.

To be more explicit, I was thinking: if `array.blockdims[axis] == (5, 8, 10)`, then the result of any array based indexing `result = array[key]` satisfies `max(result.blockdims[axis]) <= 10`.

**Comment by mrocklin** [comment]
Yeah, nm, it's just a performance concern.  We might still have problems when someone indexes with 

    x[[1000000, 1, 50000, 3, ...]]

All of the blocks would be smallish, as you say, but the scheduler is likely to hold on to things longer than we'd like

**Comment by mrocklin** [comment]
Hrm, The way we handle out-of-order lists I'm not sure there is much to be gained here.  We're going to end up pulling a lot of the data in to memory regardless.

Instead, I suggest a short-cut route in the case where the list is sorted (this is fast to check) in which case we stay within the original block structure.

**Comment by shoyer** [comment]
Sounds good to me. I think the sorted case will be quite common.
