### ISSUE TITLE
dask.distributed should have a function like IPython.parallel's "apply"

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/dask#244]
I need this so I can tell the workers to download some files they will need locally. There are probably other times we will need this to setup something on the workers.

**Comment by mrocklin** [comment]
Yes, that might make sense.  Alternatively if we were to end up tying ourselves to something like ipython parallel (which we probably wouldn't do) then we could always rely on ipython parallel to do this work for us.

**Comment by minrk** [comment]
If you are already relying on dill/cloudpickle, a simple version of this should be pretty straightforward, especially if you can guarantee that the arguments are small (e.g. paths or URLs rather than arrays). In those cases, you can build simple messages with `content = pickle.dumps(dict(f=f, args=args, kwargs=kwargs))`

Almost all of IPython's complexity comes from the async implementation. If you can manage to assert any of:

- wait for reply
- ignore reply
- request results explicitly, rather than expect them to be pushed back to you

It gets a lot simpler

**Comment by minrk** [comment]
For instance, [here's a simple demo](https://github.com/minrk/rapply) of apply over zmq, which blocks on the results. To ignore results, simply remove the reply.

**Comment by mrocklin** [comment]
I'm not too worried about implementing such an operation (there are enough operations things as-or-more-complex in the client/scheduler/worker system.)  I'm more concerned about whether or not we want to get in the business of "do this there now please" style execution.  Mostly I think that this comes down to practical use cases. 

If the use case is "tell a worker to download a file that it will need for a computation" then I would suggest that should probably be a task in a task graph, and not something that we procedurally tell the workers to do.  I would rather focus on making it easy to encode "download these files" task and incorporate them directly into the graph, hence #241 #242 .

@cowlicks are you running into use cases where a solution of one of those two issues wouldn't suffice?

**Comment by cowlicks** [comment]
@mrocklin no. I think that those methods are the right way to go. It should be easy to have `from_s3` with globbing too.
