### ISSUE TITLE
Sparse Out of Core Matrix Extension

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [ContinuumIO/dask#246]
Hi,

The company I work for has me writing sparse matrices that are out of core. I asked SciPy if they would like the code, but I was recommended to ask you if you would like it. My company gave me permission to share.

Below is a link to the current code. I am currently porting from C++ where our code previously was. I would be willing to take maintain the sparse matrices in parallel with my work.

https://github.com/aidan-plenert-macdonald/scipy/tree/master/scipy/dsparse

Let me know what plans you have.

**Comment by cowlicks** [comment]
Hello @aidan-plenert-macdonald we have been meaning to investigate sparse matrices (see #174). 

If I understand correctly, you implemented an out of core dictionary, and you are using it to make Dictionary of Key (DOK) matrices? Basically replacing the use of the in-memory dictionary with an out-of-core dictionary? Do plan to implement other formats?

We have used an out-of-core dictionary library called [chest](
https://github.com/continuumIO/chest).

**Comment by aidan-plenert-macdonald** [comment]
Yeah, I implemented a out of core dictionary with Sqlite. I didn't know about your project, but I could switch over to chest.

Yes, I plan on implementing at least the csc and csr from the link below. Or current plan was to get these compatible with Theano for the machine learning benefit. 
http://docs.scipy.org/doc/scipy/reference/sparse.html

My implementation doesn't support multi-threading very well, which would be essential. Ideally, I would also like to have it support some sort of distributed computing (MPI, Condor, Hadoop). Which one, I am not sure. I have used a Beowulf style distribution, but I want to look at others as well.

**Comment by cowlicks** [comment]
Implementing these with dask would allow multi-threading and be out-of-core. Your current implementation of DOK would have to be adapted to use dask (not just chest) to be included.

We have a very new distributed scheduler that currently unstable, broken, and untested. But it could eventually be useful for disributed memory environments. Here are [docs](http://dask.pydata.org/en/latest/distributed.html) and here is the [code](https://github.com/ContinuumIO/dask/tree/master/dask/distributed). But please don't count on this.

You should read about how dask works in the [overview](http://dask.pydata.org/en/latest/index.html).
There are two main things, schedulers and collections. Collections ([like dask.array](https://github.com/ContinuumIO/dask/tree/master/dask/array)) build up Directed Acyclic Graphs (DAGs) of "tasks". You would be adding the dask.sparse collection. Then schedulers ([like dask.async](https://github.com/ContinuumIO/dask/blob/master/dask/async.py)) execute the DAG in different ways, multi-threaded, multi-process, distributed-memory, etc.

There are two ways I can think of to go about building `dask.sparse`:

* You could re-implement each format using `dask.array` where `scipy.sparse` used numpy arrays. 
* You could stitch together `scipy.sparse` matrices of each format. This is basically what we did in `dask.array`. For example `dask.array.ones((16, 16), chunks=(4, 4))` would create 4 "tasks" that each create a smaller 4x4 numpy array of ones.

There are probably other ways to do this, but this is just what comes to mind. Some formats might be better implemented the former way, others the latter. I don't know.

Please let me know if you have more questions.

**Comment by mrocklin** [comment]
Hi Aiden.  Nice library.  It looks like you have a fully formed implementation here. If your goal is to publish that code then I would do it as a standalone project instead of trying to integrate it into another framework.

Dask collections tend to be built with dask in mind.  This is a bit different from SciPy which historically served as a repository for many interesting projects such as yours.  With the improvement of package management tools SciPy accretion has slowed a bit and people have preferred to publish on github as a small repository and on PyPI.  Both of these are relatively straightforward.

If you're interested in building a blocked sparse matrix collection using dask then that'd be grand, but that seems a bit orthogonal to this current work.  If you're interested in finding a home for your existing code then this repository probably isn't the right fit (making your own probably is) and in that case then I suggest that we close this issue.  If you are interested in building a dask-based sparse matrix implementation then I suggest that further conversation continue in #174 .

**Comment by aidan-plenert-macdonald** [comment]
Sounds good. I like your project so far. I'll take a look at more of the code, but I would be interested in writing this code for dask. I will write in #174

**Comment by nouiz** [comment]
@aidan-plenert-macdonald if you want to have something compatible with Theano, I suggest that you email theano-dev to talk about this. This week is pretty busy for us with our biggest deadline this Friday. Next week would be better.
