### ISSUE TITLE
dask.array.concatenate

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#28]
Really two issues here

1.  We should implement a `concatenate` function that concatenates many `dask.Array` objects into a single one.  This is relatively straightforward.
2.  We need to think about how users should specify collections of arrays as a single `dask.Array` 

For example given a directory of netCDF files, each with several datasets, we might want something magical like the following

    into(da.Array, '/data/myfile.*.h5::/data/path/to/X', blockshape=(1, 1000, 1000))

Or maybe this is too magical.  Maybe we need to have a more verbose function that allows users to specify their intent more precisely.  One approach with `concatenate` would be

    uris = [fn + '::/data/path/to/X' for fn in sorted(glob('./data/myfile.*.h5'))]
    arrays = [into(Array, uri, blockshape=(1000, 1000)) for uri in uris]
    arr = da.stack(arrays, axis=0)

I'd value @shoyer 's opinion here.

**Comment by shoyer** [comment]
There are two common ways to combine arrays:

1. along an existing dimension (`np.concatenate`)
2. along a new dimension (`np.array`)

I would design an explicit API that makes clear distinctions between the two. I'm all for shortcuts, but it is not obvious from your first example which is intended. (This is a little easier in xray where we can put both these into `concat` because we have dimension names, but we still need the user to supply the name of the dimension to concatenate along.)

**Comment by mrocklin** [comment]
Is there an alternative to the name `array` for "stack along a new dimension" that doesn't conflict with other common names?

**Comment by shoyer** [comment]
In biggus they use the name `stack` for "stack along a new dimension". That would probably be my first choice (though clearly the meaning of stack is not obviously different from concatenate, e.g., see your second example).

**Comment by shoyer** [comment]
See http://biggus.readthedocs.org/en/latest/creation.html#combining-arrays

**Comment by mrocklin** [comment]
BTW, I also added concatenate.
