### ISSUE TITLE
readthedocs dask.bag.api documentation is not autogenerating

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/dask#284]

**Comment by mrocklin** [comment]
Not sure why this is.  http://dask.readthedocs.org/en/latest/array-api.html is also broken

**Comment by mrocklin** [comment]
This might be an appropriate question for stackoverflow or a rtd user mailing list (if it exists)

**Comment by shoyer** [comment]
I am 95% sure this is https://github.com/sphinx-doc/sphinx/issues/1822

For now, the work around is to add `sphinx=1.2.3` to requirements.txt.

**Comment by mrocklin** [comment]
This doesn't seem to have resolved the problem 

http://dask.readthedocs.org/en/latest/bag.html#api
https://github.com/ContinuumIO/dask/commit/507bfea62762f183a70a21150e2766ab1b3628cf

**Comment by cowlicks** [comment]
Is there another way of debugging this than using dask master and our public readthedocs? I don't  think there is and that makes debugging this a pain.

Maybe I could setup an alternate RTD (if they are free) that points to my fork of dask. That is probably too much of a time sink. But it would be educational.

**Comment by shoyer** [comment]
I have some experience with this, can post some guidance later.

**Comment by mrocklin** [comment]
Personally I would just push to master.  It's not clean, but doesn't have terrible lasting effects, is effective, and lets us get on to other work quickly.

**Comment by shoyer** [comment]
You can experiment with another branch, if you like -- RTD has an option to build alternate docs from other branches than master.

**Comment by shoyer** [comment]
So basically, you need to wipe your build environment on RTD, e.g., from this page:
https://readthedocs.org/wipe/continuumio/dask/

Then rebuild manually at https://readthedocs.org/builds/dask/ -- possibly multiple times, if necessary.

**Comment by mrocklin** [comment]
The wipe link seems to be broken.  Just in case you have loads of free time I've given you access to the dask's rtd project :)

**Comment by shoyer** [comment]
OK, I'll give it a try...

BTW, looks like readthedocs finally added a GUI for the wipe link -- you can find it from the "versions" tab on the project page.

**Comment by shoyer** [comment]
OK, I got everything working. For future reference, here's what I had to do.

First, I enabled the "use a virtualenv" and "use system packages" options on RTD:

![screen shot 2015-06-12 at 10 54 44 am](https://cloud.githubusercontent.com/assets/1217238/8137313/57e22818-10f7-11e5-9251-9b132c2dd51e.png)

The former allows you to install custom dependencies; the later means that you get some pre-built packages preinstalled (slightly old numpy, scipy and matplotlib) so you don't need to build them yourself using pip (which would almost certainly fail).

Then, I updated the RTD requirements.txt file to include all the requirements for dask subprojects:
https://github.com/ContinuumIO/dask/blob/master/docs/requirements-docs.txt

I committed those changes directly to master.

Also @mrocklin -- note that you have a pin dependencies in pip like `sphinx==1.2.3`, not `sphinx=1.2.3`

Going forward, I would recommend considering using the [ipython directive](http://matplotlib.org/sampledoc/ipython_directive.html) to execute code on demand when the docs are built, instead of needing to save the output in the `.rst` files. This works really nicely for the xray and pandas docs. Though, obviously, there will be some cases where this isn't possible, e.g., we're probably never going to able to use h5py on RTD unless they support conda.

**Comment by mrocklin** [comment]
<3

**Comment by mrocklin** [comment]
This looks good.  Going to start exposing other api pages in a bit.  Thank you for doing this @shoyer !

The ipython directive looks cool.  I'd be down to convert.  Probably won't go out of my way to do this in the immediate future but will keep it in mind next time I flow through things.

Closing.
