### ISSUE TITLE
DateTime Conversion/General Column Conversion

### ISSUE THREAD

**Issue by quasiben** [ContinuumIO/dask#335]
Dask currently has no methods to convert dtype of an existing column.   These is fairly common:

```
pd.to_datetime()
df.date.astype(np.datetime64)
```

I had to reach a bit to get similar behavior:

```
ddf = ddf.assign(nDate=dd.Date.map(np.datetime64))
```

**Comment by cpcloud** [comment]
I think this could be implemented using `elemwise`.

**Comment by mrocklin** [comment]
Looking through the `pd.Series` interface I also find the following:

- [ ] `dropna`
- [ ] `fillna`
- [ ] `between`
- [ ] `clip`
- [ ] `notnull/nonzero`
- [ ] `sample(frac)`
- [ ] `where`

These and others would be trivial to do once one got into the swing of things.  In general I don't think we should just copy over functionality because we can (this leads to wasted work) but if there is some way to do this easily it might be worth it.

**Comment by mrocklin** [comment]
I'll try to handle this after join stuff.
