### ISSUE TITLE
Get worker count and other info from client.

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/dask#355]
Something like this would be useful. It could count all currently registered workers.
```python
class Client():
    ...
    def get_nworkers():
        # return number of workers.
```

Another useful method could be `Client.count_active_workers` which would ping all workers, then return how many responded after 1 second or so.

**Comment by mrocklin** [comment]
Would we want to expose the full `Scheduler.workers` dict?  If so then that would be one protocol back and forth and then lots of simple functions client-side.

Could we use heartbeats (which has other uses) plus sending the `workers` dict (which might hold `"last-seen"` values) rather than making a special protocol to ping all workers and see how many respond in a second?

For maintenance concerns I'm trying to find the fewest possible protocols that can cover our needs.

**Comment by cowlicks** [comment]
Maybe `Client.registered_workers` should be a property that gets the `Scheduler.workers` dict?

**Comment by mrocklin** [comment]
Yeah, I think that it would be good to expose getting an updated workers dict.  I can think of a few use cases for this so I think it makes sense to peel this off from Client registration.

I heard once that it's good form to avoid using properties with things that are expensive and use explicit functions like `get_registered_workers()` instead.  I guess the idea was that properties look like fields which make the promise of cheap access.
