### ISSUE TITLE
dataframe read_csv (ValueError:  Exception in remote process  could not convert string to float)

### ISSUE THREAD

**Issue by bobhaffner** [ContinuumIO/dask#385]
I have a csv that contains US zip codes.  Most of them are numerics, but some of them contain hyphens (e.g. 94103-2585).

I get the following error using read_csv()
ValueError:  Exception in remote process could not convert string to float: '94103-2585'

An easy workaround for me was to include a dtype arg (dtype={"Zip Code" : "object"}.  Also, same file with pandas read_csv() correctly infers the object type.

Let me know if additional details are needed

Thanks,
Bob

dask 0.6.0
python 3.4

**Comment by mrocklin** [comment]
Sorry for the lateness in reply.

The `dask.dataframe.read_csv` guesses types based on the first thousand lines of the file.  If this isn't enough to get a clear picture of the dtypes involved you can increase the number of lines to sample with the following keyword argument:

    sample_nrows=10000

This will take a bit longer as we create the graph but might resolve the problem.  Explicitly providing the `dtype` arg is even more robust.

I'm not sure what we can do in this case short of reading the entire file to create the graph.  This is sufficiently costly that I'm not sure it would be desired.

**Comment by bobhaffner** [comment]
Agreed. dtype arg is the way to go.  Appreciate the response

**Comment by mrocklin** [comment]
I had starred this in my e-mail but it was swept away to the bowels of the second page before I looked at it again.  I only ran across this in a general sweep of dask issues.  If this happens again please ping or feel free to e-mail me directly.

Closing.

**Comment by arnaud-fossop** [comment]
Hello,
I am trying to read multiple parquet files (I created them by partitioning in 64 parts a big data file originally contained in feather formatted file) at once using dask-distributed. The reading fails with a similar error, it is worded like this:
```
distributed.worker - WARNING -  Compute Failed
Function:  read_parquet_part
args:      (<function FastParquetEngine.read_partition at 0x7f6196239f80>, <fsspec.implementations.local.LocalFileSystem object at 0x7f6196234a10>, Empty DataFrame
Columns: [...,
kwargs:    {}
Exception: ValueError("could not convert string to float: '1994-04-01'")
```
I have to note that I was successful before using a randomly half sample of this same data partitioned in 32 parts.
Unfortunately, I cannot share the data that lead to that error because they are privileged, but it would be greatly appreciated if someone can give me an idea of where to begin investigate.

I try to check the data types, they look the same, Unfortunately I don't have a way to investigate all the data in each category types in the 64 files (I have more 250 columns and several of them are categorical). I don't know enough of the parquet options to be sure that all partitioned files have the same metadata as the others (I'm producing these files using pandas).

I am using dask 2.12, python 3.7.
 
Thanks for your help
Arnaud

**Comment by TomAugspurger** [comment]
I'd recommend trying to read each file individually using pandas. You should be able to use Fastparquet or pyarrow directly to read just the metadata, but I don't recall exactly how right now.

**Comment by arnaud-fossop** [comment]
Great, I just saw that by creating a ParquetFile object with the file or the list of partition files in parameter, I just upload the metadata.

I'll try to investigate using that :)

Thanks a lot for the tip!
Arnaud
