### ISSUE TITLE
CyToolz support

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/dask#47]
I tried to install CyToolz as a dependency, but it appears that you use Toolz. Do you find Toolz better than CyToolz in your case or would CyToolz work just as well? If it is the former, could you share your insight with us? If it is the latter, could we have CyToolz support, as well? Thanks.

**Comment by mrocklin** [comment]
The places where we would use `*toolz` are not performance critical.  I <3 `cytoolz` but a vanilla windows install can't easily build it so I stick to `toolz` when performance is unimportant.  Note that `dask.bag` does use `cytoolz` for performance critical parts.  These parts are defended with try-except blocks.

I also generally assume that anyone who is willing/able to install cytoolz would also be willing/able to install toolz.

**Comment by jakirkham** [comment]
> The places where we would use `*toolz` are not performance critical.

You would know better than I.

>  I <3 `cytoolz` but a vanilla windows install can't easily build it...
> I also generally assume that anyone who is willing/able to install cytoolz would also be willing/able to install toolz.

Reasonable. I guess I was hoping that if I had `cytoolz` installed already we could skip the install `toolz` step and use `cytoolz` as a replacement.

> Note that `dask.bag` does use `cytoolz` for performance critical parts. These parts are defended with try-except blocks.

I see that now. Also, I noted that you have an `import doesnotexist` ([core.py#L12](https://github.com/ContinuumIO/dask/blob/97beea6c853e4ee05063549bd19346b6c3afaf96/dask/bag/core.py#L12)). I'm assuming the module does not exist. Is there some reason for this?

**Comment by eriknw** [comment]
CyToolz is a drop in replacement for Toolz in CPython (and if it's not, any material difference is considered a bug and will be fixed when reported).

There are three main differences between `toolz` and `cytoolz` (other than performance and installation requirements):

1. More limited introspection (such as viewing source code of a function) for `cytoolz`.
2. More limited stack traces when an exception occurs within a `cytoolz` function.
3. `cytoolz` only works with the CPython interpreter.  Since `toolz` is pure Python, it can work with any Python interpreter such as PyPy or Jython.

Regarding the `toolz`/`cytoolz` relationship, we haven't come up with a way to have `cytoolz` *replace* `toolz` automagically.  Per the Zen of Python, "Explicit is better than implicit."  `try: import cytoolz ; except: import toolz` may not be regarded as pretty, but it is easy to understand and is explicit.  Another option is to have a `mypackage.toolz` namespace in a package that imports everything from `cytoolz` if available, else it imports from `toolz`.  A separate package such as `from best_available_toolz import *` could serve the same purpose, but you'd probably want a shorter name.  If you have any ideas or suggestions on this topic, please share!

**Comment by mrocklin** [comment]
> I see that now. Also, I noted that you have an import doesnotexist (core.py#L12). I'm assuming the module does not exist. Is there some reason for this?

Ah, thank you.  This was left over from some debug work and it looks like it was accidentally meged in.  Fixed in https://github.com/ContinuumIO/dask/commit/b5459c9a57626a8480ad122853c0edc88d39842a

**Comment by cpcloud** [comment]
A simple way to transparently use `cytoolz` is to just call everything `toolz`:

```python
try:
    import cytoolz as toolz
except ImportError:
    import toolz
```

**Comment by mrocklin** [comment]
I can imagine a world where we have `cytoolz`, `pytoolz` packages along with a very thin `toolz` package that was just 

```python
try:
    from cytoolz import *
except ImportError:
    from toolz import *
```

Alternatively I wouldn't mind importing certain functions from toolz (like `pipe`) and others from cytoolz (like `get`)

**Comment by jakirkham** [comment]
Before I respond, let me say I think this is a really interesting package and have already started playing with it. I am very excited to see how it develops. Sorry this response took awhile.

> CyToolz is a drop in replacement for Toolz in CPython (and if it's not, any material difference is considered a bug and will be fixed when reported).

Excellent. That all sounds good.

> There are three main differences between toolz and cytoolz (other than performance and installation requirements)

Yep, that all makes sense, as well. It was the performance, in particular, that I was interested in here.

> Regarding the toolz/cytoolz relationship, we haven't come up with a way to have cytoolz replace toolz automagically. Per the Zen of Python, "Explicit is better than implicit."

Absolutely agree. I think what you did was right. Your suggestions sounded good. In fact, I was about to suggest one of them here, namely "have a mypackage.toolz namespace in a package that imports everything from `cytoolz` if available, else it imports from `toolz`".

The main reason I was thinking about this suggestion, in particular, is I saw [core.py#L8-L10](https://github.com/ContinuumIO/dask/blob/97beea6c853e4ee05063549bd19346b6c3afaf96/dask/bag/core.py#L8-L10) and [core.py#L13-L14](https://github.com/ContinuumIO/dask/blob/97beea6c853e4ee05063549bd19346b6c3afaf96/dask/bag/core.py#L13-L14). Now, admittedly, I have dug to deep here, but I'm sure the ones that are being imported from `cytoolz` are the performance critical ones and the ones imported from `toolz` are not. My main worry is as more hands get in the code it might become less obvious that some function is performance critical and should be in the second list (i.e. it is already imported and somebody uses it in some code next we have a surprise bottleneck).

> More limited introspection...More limited stack traces...

Though you have raised some very good points here, so I think whatever solution is used should make sure to address these issues. I'm less worried about the third point due to the use cases for `dask`, but if we have a solution for the first two it should apply equally well in the last case.

Here is my suggestion, feel free to give me feedback. By default, `dask` should use `toolz`. This is basically what it does anyways and that is fine. This allows good feedback for the developer, easy use in iPython (with good feedback), works great on tests, easy to install, no Windows pains, and so on. However, `dask` should have `dask.toolz` this imports all of `toolz` as you have said. However, we provide a flag that goes in `dask.__init__` like `use_cytoolz`, which defaults to `False`. The user can then do the following.

    import dask
    dask.use_cytoolz = True
    ....

This, I feel, provides the best of both worlds. By default, debugging works nicely and seamlessly. Optimizations are available as option. Additionally, if cytoolz is not there, a fallback to pytoolz can occur like you have suggested followed by an `ImportWarning` stating cytoolz wasn't found on the path (perhaps even using the message from the `ImportError`).

**Comment by mrocklin** [comment]
I'm not yet very concerned about people accidentally choosing the wrong place to import a function.  This is for a few reasons

1.  We don't yet have many contributors
2.  It rarely makes much of a difference in performance (most of dask is not limited by toolz performance)
3.  I don't anticipate people screwing those few lines of code that you mention

Adding a new toolz module and having global flags seems like premature optimization at this point.  The fix is about as complex as the problem.

I could be wrong though.  Toolz feels pretty natural to me so I'm likely to undervalue it's complexity.

**Comment by shoyer** [comment]
My vote would be for using @cpcloud's solution. It's a little unexpected to need to install both.

**Comment by mrocklin** [comment]
That expectation can be mediated by adding both as dependencies.  Dask is a little strange with dependencies right now because `dask.bag` and `dask.array` are effectively separate projects with different dependency needs.  I suspect that this issue would not have arisen had I put all requirements in `requirements.txt`.

**Comment by jakirkham** [comment]
I'd like to add that my previous comment probably is more relevant for toolz/cytoolz and however they might be integrated in the future. In particular, it was responding to concerns @eriknw raised.

As for solving this issue, I'd be happy with anything anyone has mentioned previously along the lines of `try: ... except: ...` imports that prefer `cytoolz`. Honestly, having a module called something `dtoolz` with @mrocklin's previous suggestion would be good for solving the problem while avoiding clutter, but I'm not picky. Also, as @shoyer mentioned, if an acceptable version of `cytoolz` or `toolz` is detected, the additional install should be skipped and one should be used.

**Comment by mrocklin** [comment]
I'm going to close this.  It's stale and I don't anticipate changing anything on the dask end in the immediate future.  Toolz remains useful for projects that don't want to depend on cython code.  This is critical to support the naive windows user.  Workarounds for this problem seem more complex than just adding toolz in requirements which is very lightweight.
