### ISSUE TITLE
Profiler fails with KeyError with dask.bag + dask.do

### ISSUE THREAD

**Issue by cpcloud** [ContinuumIO/dask#497]
Here's a snippet that reproduces the issue

```python
import dask.bag as db
from dask import do
from dask.diagnostics import Profiler


def inc(x):
    return x + 1


@do
def dec(seq):
    return [x - 1 for x in seq]

bag = dec(db.from_sequence([1, 2, 3]).map(inc))

result = bag.compute()
assert result == [1, 2, 3]  # works

with Profiler() as prof:
    result = bag.compute()  # somehow fails because of the profiler
```

I suspect this is related to using both thread and process based schedulers

**Comment by mrocklin** [comment]
This is also fairly strange behavior.  You're wrapping one dask thing with another.

I suggest that dask calling dask is something of an anti-pattern.  You really want to merge graphs, not nest them.

**Comment by cpcloud** [comment]
happy to chalk it up to user error, should i close?

**Comment by mrocklin** [comment]
I'm curious what the behavior was that lead to this error.  The fact that you got to this state is an error in documentation.

**Comment by jcrist** [comment]
The reason the profiler errors is because it's recording all computations in the dask, but then only working with the outermost dask. Definitely user error, not sure how we'd deal with this otherwise.

In the future I plan to make imperative play nice with the collections, so then doing it this way should work as you expected. Until then though we should update the docs to say not to mix collections.
