### ISSUE TITLE
ProgressBar doesn't exit cleanly on error

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#500]
When call to get terminates abruptly due to an error in one of the tasks the progressbar continues counting off time.  Presumably we should call the finalize callback when we encounter an error.

**Comment by jcrist** [comment]
Hmm, that is a problem. Calling `finish` on error seems wrong to me though, as there's no way to distinguish between an error and the actual end of task. I see three solutions to this:

- Add yet another callback to get called on errors. Could potentially call it `cleanup` or something, and have it called at the end as well. I imagine this taking no parameters.
- Handle this in the `__exit__` method of `Profiler`. Unfortunately this will fail if the callbacks are set globally instead of contextually.
- Modify `finish` to take a third parameter that's either `None` or the traceback. This would work, but destroys the symmetry between `start` and `finish`.

I'd prefer either the 1st or 3rd option.

**Comment by mrocklin** [comment]
In current code is there anything that would break by calling `finish` on error?

**Comment by jcrist** [comment]
None at all. I would want to add a parameter though to note whether it was a clean finish or not. Could be boolean, or include the traceback (thinking about it's uses, I think I'd actual prefer the parameter to be `clean_finish` or `errored`, and boolean).

**Comment by mrocklin** [comment]
I trust your judgement here more than my own.
