### ISSUE TITLE
Optimization to remove aliases

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#53]
Sometimes we create dasks with aliases

```python
{'a': 1, 'b': 'a', 'c': (inc, 'b')}
```

In these cases it would remove some work from the schedulers if we could short circuit the unnecessary alias

```python
{'a': 1, 'c': (inc, 'a')}
```

**Comment by eriknw** [comment]
Since when do we create dasks with aliases?  This is not in the docs nor is it tested.

**Comment by mrocklin** [comment]
See https://github.com/mrocklin/dask/commit/5869ac84685f9d3e5ed0679886474e745768cbe5 .  This isn't in yet.

**Comment by mrocklin** [comment]
That commit stops us from doing a lot of unnecessary `y = x[:, :]` .  The ghosting code is pretty liberal about making lots of full slices.  I want a way to clean this up afterwards.  The async scheduler is fine with these aliases.  The core schedulers are not.  My hope is that it's easy to clean them up before we ever get there.

**Comment by eriknw** [comment]
hmm, okay.  Aliases may break some internal functions, since this wasn't part of the original model of a dask (as I understood them anyway).  This clobbers the values of a dask, which now may be literals or a key.  Previously, a literal could be inferred as "not a task".

Perhaps aliases can be defined like `{'a': 1, 'b': ['a'], 'c': (inc, 'b')}`, although it's unclear whether `'b'` should be an `Iterable` or not.  This make something like this valid, and we would expect `'c'` to be an `Iterable`: `{'a': 1, 'b': 2, 'c': ['a', 'b'], 'd': (sum, 'c')}`.

**Comment by mrocklin** [comment]
We could also keep the old semantics and always clean up this one function.  That way we don't ever expose illegal dasks.

**Comment by eriknw** [comment]
That was my next suggestion (after looking at the branch) :).

Internally, we could do something like `{'a': 1, 'b': (identity, 'a'), 'c': (inc, 'b')}` and then clean it up accordingly.  iirc, we did something like this by removing unnecessary calls to `list`.

**Comment by eriknw** [comment]
Actually, this works out of the box:
```python
In [1]: import dask.optimize

In [2]: def inc(x): return x+1

In [3]: d = {'a': 1, 'b': 'a', 'c': (inc, 'b')}

In [4]: dask.optimize.inline(d, keys='b', inline_constants=False)
Out[4]: {'a': 1, 'c': (<function __main__.inc>, 'a')}
```
So, just keep track of which items are aliases, then inline 'em.

**Comment by mrocklin** [comment]
Oh.  Great.

**Comment by mrocklin** [comment]
This became slightly more complex due to aliases at the end of the DAG whose names we might have to remember.  These need to be sort of reverse-inlined.  I have a workable solution in my ghost branch.
