### ISSUE TITLE
ProgressBar is not visible in the notebook

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#531]
The `ProgressBar` doesn't update itself during execution while in the notebook.  Afterwards the full bar will pop up but it doesn't give you any cues during execution.

**Comment by mrocklin** [comment]
Here was my testing cell

```python
from dask.diagnostics import ProgressBar
from dask.async import get_sync
from time import sleep

def f(x):
    sleep(x)
    return x

dsk = {('x', i): (f, 0.2) for i in range(10)}

with ProgressBar():
    get_sync(dsk, list(dsk))
```

**Comment by jcrist** [comment]
Weird, it's because of the background thread. I specifically tested it in notebooks before originally pushing it. Commit 6d6fb216e works.

**Comment by jcrist** [comment]
This explains it a bit more in detail: http://mail.scipy.org/pipermail/ipython-dev/2014-March/013614.html

If you add a call to `sys.stdout.flush()` in `f(x)`, then the progressbar updates after each function completion. This is because zmq sockets aren't threadsafe, so the output from the background thread is buffered until the kernel is idle. The call to `sys.stdout.flush()` clears that buffer.

A few options:

- Revert back to my original implementation with no timer
- Revert back to my original implementation, but add a timer that updates only when a task completes. This will be irregular, and may have large pauses for long running tasks.
- Some magic I haven't thought of yet.

**Comment by mrocklin** [comment]
What about flushing within the post task callback?  This would hopefully be a noop in the console and would default to irregular printing in the notebook.

**Comment by jcrist** [comment]
> Some magic I haven't thought of yet.

...

> What about flushing within the post task callback? This would hopefully be a noop in the console and would default to irregular printing in the notebook.

:+1:
