### ISSUE TITLE
Use dict rather than tuple for callbacks?

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#532]
A full callback set has four functions, `_start`, `_pretask`, `_posttask`, and `_finish`.  We represent them as a tuple with four functions in that order.  

Thoughts on switching to a named entity rather than an ordered one?  Either a dict or namedtuple might be pleasant.  A dict has the advantage that one could more naturally specify a single callback or two.  I currently find myself writing

```python
def post(...)
    ...

cb = [None, None, post, None]
```

When I might prefer to write

```python
cb = {'post': post}
```

Additionally, thoughts on changing the names to `start`, `pre`, `post`, and `finish`?

cc @jcrist

**Comment by jcrist** [comment]
It already is a namedtuple: https://github.com/ContinuumIO/dask/blob/master/dask/callbacks.py#L5 (although we never use the namings...). I'm -1 on enforcing use of a namedtuple for users though, as a builtin seems easier. A dict could work, but something about strings for tags (and potentially misspelling) feels wrong to me.

On the name change, `pretask` and `posttask` mention `task` because `start` and `stop` don't. To put that clearer, without mentioning what "start" or "pre" refers to, both pairs essentially bookend an undefined interval. Adding the "task" qualifier make that clearer (IMO).

**Comment by jcrist** [comment]
My plan for the future of callback stuff is to remove `Diagnostic` in favor of something similar that will live in `callbacks.py`. This will still support the context manager things, and should be directly passable to `add_callbacks`. Probably will be just a subclass of tuple, to allow for the ordering, and normal tuples still to be used.

**Comment by mrocklin** [comment]
OK, I think that my use case was wanting to create a callback with just one function.  I'd be happy if I could write the following 

    cb = Callback(posttask=func)

**Comment by jcrist** [comment]
That's totally doable. I'll probably tackle this tomorrow.
