### ISSUE TITLE
apply function to Series, NotImplementedError

### ISSUE THREAD

**Issue by wiso** [ContinuumIO/dask#580]
Hello, here my problem to apply function to Series:

while this works:

    import dask
    d = np.arange(10)
    dd = dask.array.from_array(d, 10)
    np.cos(dd)

with dask.DataFrame it doesn't:

    import pandas as pd
    d = pd.DataFrame({'x': np.arange(10, dtype=float)})
    dd = dask.dataframe.from_pandas(d, 2)
    np.cos(d['x'])      # this works
    np.cos(dd['x'])    # this doesn't work

actually I am not able to apply any functions. I get:

    NotImplementedError                       Traceback (most recent call last)
    <ipython-input-140-69836e5dabc3> in <module>()
    ----> 1 np.cos(dd['x'])

    /usr/lib/python2.7/site-packages/dask/dataframe/core.pyc in __getitem__(self, key)
        372             return Series(merge(self.dask, key.dask, dsk), name,
        373                           self.name, self.divisions)
    --> 374         raise NotImplementedError()
        375 
        376     def __abs__(self):

    NotImplementedError:

**Comment by mrocklin** [comment]
Hi @wiso good question.  A few things.

1.  You should probably be using `da.sin` rather than `np.sin`.  The NumPy function will turn the result into a numpy array.  This might change with the next release of NumPy if they release the `__numpy_ufunc__` protocol.  Until then we have to use our own funcions, namely `da.sin`.
2.  At the moment `da.sin` doesn't play nicely with `dd.Series` objects.  It should though.  I wonder if the right thing to do here is to implement `__numpy_ufunc__` on dask array and dataframe objects in anticipation of the numpy release and then use this within our own ufuncs.

Until either of these happens you can always call the following (although this feels a bit ugly.)

    myseries.map_partitions(np.sin)

**Comment by wiso** [comment]
Ok, thank you. I am wondering why it works for dask.array but not series.

**Comment by jcrist** [comment]
Dask arrays implement the [array interface](http://docs.scipy.org/doc/numpy/reference/arrays.classes.html#special-attributes-and-methods), meaning that numpy functions coerce them into instances of `np.ndarray` before computing. We don't currently support this for `dask.dataframe` objects, but we could. 

Note that when using numpy functions like `np.sin`, the whole array will be pulled into memory and run *in serial* at call time. Dask as a library works best if you build up a graph of your computations, and then compute *in parallel*. This is why we implement `dask.array.sin`, etc... - in general these should be drop ins for the numpy versions.
